# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcommand.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(638, 365)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 40, 41, 21))
        self.label.setObjectName("label")
        self.website = QtWidgets.QLineEdit(Dialog)
        self.website.setGeometry(QtCore.QRect(110, 40, 381, 21))
        self.website.setObjectName("website")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 51, 16))
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setGeometry(QtCore.QRect(120, 110, 161, 21))
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(350, 110, 41, 16))
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(400, 110, 161, 21))
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 200, 51, 16))
        self.label_5.setObjectName("label_5")
        self.userwidget = QtWidgets.QLineEdit(Dialog)
        self.userwidget.setGeometry(QtCore.QRect(110, 200, 191, 21))
        self.userwidget.setObjectName("userwidget")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(330, 200, 51, 16))
        self.label_6.setObjectName("label_6")
        self.passwordwidget = QtWidgets.QLineEdit(Dialog)
        self.passwordwidget.setGeometry(QtCore.QRect(390, 200, 201, 21))
        self.passwordwidget.setObjectName("passwordwidget")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 250, 51, 16))
        self.label_7.setObjectName("label_7")
        self.loginwidget = QtWidgets.QLineEdit(Dialog)
        self.loginwidget.setGeometry(QtCore.QRect(110, 250, 191, 21))
        self.loginwidget.setObjectName("loginwidget")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(140, 320, 41, 16))
        self.label_8.setObjectName("label_8")
        self.comm = QtWidgets.QLineEdit(Dialog)
        self.comm.setGeometry(QtCore.QRect(190, 320, 211, 21))
        self.comm.setObjectName("comm")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(490, 320, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加口令"))
        self.label.setText(_translate("Dialog", "网址:"))
        self.label_2.setText(_translate("Dialog", "用户名:"))
        self.label_3.setText(_translate("Dialog", "密码:"))
        self.label_4.setText(_translate("Dialog", "定位控件:"))
        self.label_5.setText(_translate("Dialog", "用户框："))
        self.label_6.setText(_translate("Dialog", "密码框："))
        self.label_7.setText(_translate("Dialog", "登陆键："))
        self.label_8.setText(_translate("Dialog", "口令:"))
        self.pushButton.setText(_translate("Dialog", "提交"))


class addcommandwindow(QDialog, Ui_Dialog):

    # detect_data_signal = pyqtSignal(bytes)

    def __init__(self, parent=None):
        super(addcommandwindow, self).__init__(parent)
        self.setupUi(self)

        self.pushButton.clicked.connect(self.add)

    def add(self):

        self.website_txt = self.website.text()

        self.username_txt = self.username.text()

        self.password_txt = self.password.text  ()

        self.userwidget_txt = self.userwidget.text  ()

        self.passwordwidget_txt = self.passwordwidget . text  ()

        self . loginwidget_txt = self . loginwidget . text  ()

        self . comm_txt = self . comm . text    ()

        self . close    ()




